### ISSUE TITLE
No File: setup.py

### ISSUE THREAD

**Issue by konradSC** [AccelerateNetworks/DeepSpeech_Frontend#4]
This is very cool project! I'm excited to test it out. 

I'm running into some errors during the install though and was wondering if you had any insight. I'm running Debian 9. I'm getting the following error: 

```
(env) root@files01:/var/code/deepspeech# pip install git+https://git.callpipe.com/fusionpbx/deepspeech_frontend
Collecting git+https://git.callpipe.com/fusionpbx/deepspeech_frontend
  Cloning https://git.callpipe.com/fusionpbx/deepspeech_frontend to /tmp/pip-req-build-nf_kirmy
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/var/code/deepspeech/env/lib/python3.5/tokenize.py", line 454, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-nf_kirmy/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-nf_kirmy/
```

Should there be a setup.py file somewhere?
Thanks!

**Comment by danry25** [comment]
Just added a setup.py file on e4fbc27749af527e60674c478b64cd792a7828e5, which fixed this per our conversation.
